/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `/detalle-materia`; params?: Router.UnknownInputParams; } | { pathname: `/finales`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/horarios`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/parciales`; params?: Router.UnknownInputParams; } | { pathname: `/plan-estudios`; params?: Router.UnknownInputParams; } | { pathname: `/repositorio`; params?: Router.UnknownInputParams; } | { pathname: `/simulador`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `/detalle-materia`; params?: Router.UnknownOutputParams; } | { pathname: `/finales`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/horarios`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/parciales`; params?: Router.UnknownOutputParams; } | { pathname: `/plan-estudios`; params?: Router.UnknownOutputParams; } | { pathname: `/repositorio`; params?: Router.UnknownOutputParams; } | { pathname: `/simulador`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/agenda${`?${string}` | `#${string}` | ''}` | `/detalle-materia${`?${string}` | `#${string}` | ''}` | `/finales${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/horarios${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/parciales${`?${string}` | `#${string}` | ''}` | `/plan-estudios${`?${string}` | `#${string}` | ''}` | `/repositorio${`?${string}` | `#${string}` | ''}` | `/simulador${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `/detalle-materia`; params?: Router.UnknownInputParams; } | { pathname: `/finales`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/horarios`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/parciales`; params?: Router.UnknownInputParams; } | { pathname: `/plan-estudios`; params?: Router.UnknownInputParams; } | { pathname: `/repositorio`; params?: Router.UnknownInputParams; } | { pathname: `/simulador`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
